<?php
declare(strict_types=1);

namespace ConorSmith\Hoarde\Infra\Repository;

use ConorSmith\Hoarde\Domain\Construction;
use ConorSmith\Hoarde\Domain\Coordinates;
use ConorSmith\Hoarde\Domain\Entity;
use ConorSmith\Hoarde\Domain\Inventory;
use ConorSmith\Hoarde\Domain\Location;
use ConorSmith\Hoarde\Domain\LocationTemplate;
use ConorSmith\Hoarde\Domain\LocationTemplateRepository;
use ConorSmith\Hoarde\Domain\ResourceNeed;
use ConorSmith\Hoarde\Domain\ResourceRepository;
use ConorSmith\Hoarde\Domain\VarietyRepository;
use Ramsey\Uuid\Uuid;
use Ramsey\Uuid\UuidInterface;

final class LocationTemplateRepositoryConfig implements LocationTemplateRepository
{
    private const CONFIG = [
        "12,30"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "10,29"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "11,29"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "12,29"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "7,28"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "8,28"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "9,28"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "10,28"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "11,28"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "12,28"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "6,27"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "7,27"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "8,27"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "9,27"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "10,27"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "11,27"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "12,27"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "5,26"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "6,26"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "7,26"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "8,26"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "9,26"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "10,26"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "11,26"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "12,26"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "4,25"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "5,25"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "6,25"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "7,25"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "8,25"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "9,25"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "10,25"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "11,25"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "2,24"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "3,24"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "4,24"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "5,24"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "6,24"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "7,24"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "8,24"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "9,24"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "10,24"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "11,24"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "1,23"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "2,23"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "3,23"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "4,23"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "5,23"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "6,23"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "7,23"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "8,23"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "9,23"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "10,23"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "11,23"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "1,22"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "2,22"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "3,22"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "4,22"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "5,22"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "6,22"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "7,22"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "8,22"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "9,22"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "10,22"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "11,22"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "1,21"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "2,21"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "3,21"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "4,21"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "5,21"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "6,21"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "7,21"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "8,21"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "9,21"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "10,21"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "11,21"   => ['biome' => BiomeRepositoryConfig::URBAN,],
        "0,20"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "1,20"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "2,20"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "3,20"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "4,20"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "5,20"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "6,20"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "7,20"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "8,20"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "9,20"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "10,20"   => ['biome' => BiomeRepositoryConfig::URBAN,],
        "11,20"   => ['biome' => BiomeRepositoryConfig::URBAN,],
        "0,19"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "1,19"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "2,19"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "3,19"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "4,19"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "5,19"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "6,19"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "7,19"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "8,19"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "9,19"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "10,19"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "11,19"   => ['biome' => BiomeRepositoryConfig::URBAN,],
        "12,19"   => ['biome' => BiomeRepositoryConfig::URBAN,],
        "-1,18"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "0,18"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "1,18"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "2,18"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "3,18"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "4,18"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "5,18"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "6,18"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "7,18"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "8,18"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "9,18"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "10,18"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "11,18"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "12,18"   => ['biome' => BiomeRepositoryConfig::URBAN,],
        "13,18"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-1,17"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "0,17"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "1,17"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "2,17"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "3,17"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "4,17"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "5,17"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "6,17"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "7,17"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "8,17"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "9,17"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "10,17"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "11,17"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "12,17"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "13,17"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "14,17"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "15,17"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-1,16"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "0,16"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "1,16"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "2,16"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "3,16"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "4,16"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "5,16"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "6,16"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "7,16"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "8,16"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "9,16"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "10,16"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "11,16"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "12,16"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "13,16"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "14,16"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-1,15"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "0,15"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "1,15"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "2,15"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "3,15"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "4,15"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "5,15"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "6,15"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "7,15"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "8,15"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "9,15"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "10,15"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "11,15"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "12,15"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "13,15"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "14,15"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-2,14"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-1,14"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "0,14"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "1,14"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "2,14"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "3,14"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "4,14"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "5,14"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "6,14"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "7,14"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "8,14"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "9,14"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "10,14"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "11,14"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "12,14"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "13,14"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-2,13"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-1,13"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "0,13"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "1,13"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "2,13"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "3,13"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "4,13"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "5,13"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "6,13"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "7,13"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "8,13"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "9,13"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "10,13"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "11,13"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "12,13"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "13,13"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-4,12"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-3,12"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-2,12"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-1,12"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "0,12"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "1,12"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "2,12"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "3,12"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "4,12"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "5,12"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "6,12"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "7,12"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "8,12"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "9,12"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "10,12"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "11,12"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "12,12"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-5,11"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-4,11"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-3,11"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-2,11"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-1,11"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "0,11"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "1,11"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "2,11"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "3,11"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "4,11"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "5,11"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "6,11"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "7,11"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "8,11"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "9,11"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "10,11"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "11,11"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "12,11"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-6,10"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-5,10"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-4,10"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-3,10"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-2,10"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-1,10"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "0,10"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "1,10"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "2,10"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "3,10"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "4,10"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "5,10"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "6,10"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "7,10"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "8,10"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "9,10"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "10,10"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "11,10"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-6,9"    => ['biome' => BiomeRepositoryConfig::URBAN,],
        "-5,9"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-4,9"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-3,9"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-2,9"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-1,9"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "0,9"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "1,9"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "2,9"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "3,9"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "4,9"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "5,9"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "6,9"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "7,9"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "8,9"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "9,9"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "10,9"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "11,9"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-8,8"    => ['biome' => BiomeRepositoryConfig::URBAN,],
        "-7,8"    => ['biome' => BiomeRepositoryConfig::URBAN,],
        "-6,8"    => ['biome' => BiomeRepositoryConfig::URBAN,],
        "-5,8"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-4,8"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-3,8"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-2,8"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-1,8"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "0,8"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "1,8"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "2,8"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "3,8"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "4,8"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "5,8"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "6,8"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "7,8"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "8,8"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "9,8"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "10,8"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-8,7"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-7,7"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-6,7"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-5,7"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-4,7"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-3,7"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-2,7"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-1,7"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "0,7"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "1,7"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "2,7"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "3,7"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "4,7"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "5,7"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "6,7"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "7,7"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "8,7"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "9,7"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "10,7"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-7,6"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-6,6"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-5,6"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-4,6"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-3,6"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-2,6"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-1,6"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "0,6"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "1,6"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "2,6"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "3,6"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "4,6"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "5,6"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "6,6"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "7,6"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "8,6"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "9,6"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "10,6"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "11,6"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-8,5"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-7,5"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-6,5"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-5,5"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-4,5"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-3,5"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-2,5"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-1,5"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "0,5"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "1,5"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "2,5"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "3,5"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "4,5"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "5,5"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "6,5"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "7,5"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "8,5"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "9,5"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "10,5"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "11,5"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-9,4"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-8,4"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-7,4"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-6,4"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-5,4"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-4,4"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-3,4"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-2,4"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-1,4"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "0,4"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "1,4"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "2,4"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "3,4"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "4,4"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "5,4"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "6,4"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "7,4"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "8,4"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "9,4"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "10,4"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-10,3"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-9,3"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-8,3"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-7,3"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-6,3"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-5,3"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-4,3"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-3,3"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-2,3"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-1,3"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "0,3"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "1,3"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "2,3"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "3,3"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "4,3"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "5,3"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "6,3"     => ['biome' => BiomeRepositoryConfig::URBAN,],
        "7,3"     => ['biome' => BiomeRepositoryConfig::URBAN,],
        "8,3"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "9,3"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-10,2"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-9,2"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-8,2"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-7,2"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-6,2"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-5,2"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-4,2"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-3,2"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-2,2"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-1,2"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "0,2"     => [
            'biome' => BiomeRepositoryConfig::ARABLE,
            'entities' => [
                [
                    'varietyId' => VarietyRepositoryConfig::TOOLBOX,
                    'inventory' => [
                        [
                            'varietyId' => VarietyRepositoryConfig::JOELS_NOTE,
                            'quantity'  => 1,
                        ],
                        [
                            'varietyId' => VarietyRepositoryConfig::TINNED_SOUP,
                            'quantity'  => 1,
                        ],
                    ],
                ],
            ],
        ],
        "1,2"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "2,2"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "3,2"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "4,2"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "5,2"     => ['biome' => BiomeRepositoryConfig::URBAN,],
        "6,2"     => ['biome' => BiomeRepositoryConfig::URBAN,],
        "-8,1"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-7,1"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-6,1"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-5,1"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-4,1"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-3,1"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-2,1"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-1,1"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "0,1"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "1,1"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "2,1"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "3,1"     => [
            'biome' => BiomeRepositoryConfig::ARABLE,
            'entities' => [
                [
                    'varietyId' => VarietyRepositoryConfig::HUMAN,
                    'label'     => "Joel",
                    'isIntact'  => false,
                    'inventory' => [
                        [
                            'varietyId' => VarietyRepositoryConfig::HAMMER,
                            'quantity'  => 1,
                        ],
                    ],
                ],
            ],
        ],
        "4,1"     => ['biome' => BiomeRepositoryConfig::URBAN,],
        "5,1"     => ['biome' => BiomeRepositoryConfig::URBAN,],
        "-8,0"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-7,0"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-6,0"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-5,0"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-4,0"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-3,0"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-2,0"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-1,0"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "0,0"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "1,0"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "2,0"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "3,0"     => ['biome' => BiomeRepositoryConfig::URBAN,],
        "4,0"     => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "5,0"     => ['biome' => BiomeRepositoryConfig::URBAN,],
        "-8,-1"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-7,-1"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-6,-1"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-5,-1"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-4,-1"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-3,-1"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-2,-1"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-1,-1"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "0,-1"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "1,-1"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "2,-1"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "3,-1"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "4,-1"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "5,-1"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "6,-1"    => ['biome' => BiomeRepositoryConfig::URBAN,],
        "-10,-2"  => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-9,-2"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-8,-2"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-7,-2"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-6,-2"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-5,-2"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-4,-2"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-3,-2"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-2,-2"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-1,-2"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "0,-2"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "1,-2"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "2,-2"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "3,-2"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "4,-2"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "5,-2"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-10,-3"  => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-9,-3"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-8,-3"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-7,-3"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-6,-3"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-5,-3"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-4,-3"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-3,-3"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-2,-3"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-1,-3"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "0,-3"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "1,-3"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "2,-3"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-12,-4"  => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-10,-4"  => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-9,-4"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-8,-4"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-7,-4"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-6,-4"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-5,-4"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-4,-4"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-3,-4"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-2,-4"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-1,-4"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "0,-4"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "1,-4"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-13,-5"  => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-12,-5"  => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-11,-5"  => ['biome' => BiomeRepositoryConfig::URBAN,],
        "-10,-5"  => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-9,-5"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-8,-5"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-7,-5"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-6,-5"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-5,-5"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-4,-5"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-3,-5"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-2,-5"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-1,-5"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "0,-5"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "1,-5"    => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-11,-6"  => ['biome' => BiomeRepositoryConfig::URBAN,],
        "-10,-6"  => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-9,-6"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-6,-6"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-5,-6"   => ['biome' => BiomeRepositoryConfig::URBAN,],
        "-4,-6"   => ['biome' => BiomeRepositoryConfig::URBAN,],
        "-3,-6"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-2,-6"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-12,-7"  => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-11,-7"  => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-10,-7"  => ['biome' => BiomeRepositoryConfig::URBAN,],
        "-6,-7"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-5,-7"   => ['biome' => BiomeRepositoryConfig::URBAN,],
        "-3,-7"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-2,-7"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-13,-8"  => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-12,-8"  => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-11,-8"  => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-10,-8"  => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-9,-8"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-5,-8"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-2,-8"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-13,-9"  => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-12,-9"  => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-11,-9"  => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-5,-9"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-2,-9"   => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-12,-10" => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-2,-10"  => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-14,-11" => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-15,-12" => ['biome' => BiomeRepositoryConfig::ARABLE,],
        "-14,-12" => ['biome' => BiomeRepositoryConfig::ARABLE,],
    ];

    /** @var VarietyRepository */
    private $varietyRepository;

    /** @var ResourceRepository */
    private $resourceRepository;

    public function __construct(VarietyRepository $varietyRepository, ResourceRepository $resourceRepository)
    {
        $this->varietyRepository = $varietyRepository;
        $this->resourceRepository = $resourceRepository;
    }

    public function generateNewLocation(Coordinates $coordinates, UuidInterface $gameId): LocationTemplate
    {
        $key = "{$coordinates->getX()},{$coordinates->getY()}";

        if (!array_key_exists($key, self::CONFIG)) {
            return new LocationTemplate(
                new Location(
                    Uuid::uuid4(),
                    $gameId,
                    Uuid::fromString(BiomeRepositoryConfig::OCEAN),
                    $coordinates,
                    5
                ),
                []
            );
        }

        $config = self::CONFIG[$key];

        $locationId = Uuid::uuid4();

        $generatedEntities = [];

        if (array_key_exists('entities', $config)) {
            foreach ($config['entities'] as $entityConfig) {
                $variety = $this->varietyRepository->find(Uuid::fromString($entityConfig['varietyId']));
                $resourceNeeds = [];

                if ($variety->getId()->equals(Uuid::fromString(VarietyRepositoryConfig::HUMAN))) {
                    $resourceNeeds = [
                        ResourceRepositoryConfig::FOOD => new ResourceNeed(
                            $this->resourceRepository->find(Uuid::fromString(ResourceRepositoryConfig::FOOD)),
                            0,
                            $variety->getResourceNeedCapacities()[ResourceRepositoryConfig::FOOD],
                            600,
                            null
                        ),
                        ResourceRepositoryConfig::WATER => new ResourceNeed(
                            $this->resourceRepository->find(Uuid::fromString(ResourceRepositoryConfig::WATER)),
                            0,
                            $variety->getResourceNeedCapacities()[ResourceRepositoryConfig::WATER],
                            500,
                            null
                        ),
                    ];
                }

                $entity = new Entity(
                    $entityId = Uuid::uuid4(),
                    $gameId,
                    $locationId,
                    $variety->getId(),
                    isset($entityConfig['label']) ? $entityConfig['label'] : $variety->getLabel(),
                    $variety->getIcon(),
                    1,
                    isset($entityConfig['isIntact']) ? $entityConfig['isIntact'] : true,
                    Construction::constructed(),
                    $resourceNeeds,
                    Inventory::empty($entityId, $variety)
                );

                foreach ($entityConfig['inventory'] as $itemConfig) {
                    $entity->getInventory()->addItem(
                        $this->varietyRepository->find(Uuid::fromString($itemConfig['varietyId']))
                            ->createItemWithQuantity($itemConfig['quantity'])
                    );
                }

                $generatedEntities[] = $entity;
            }
        }

        if (array_key_exists('biome', $config)) {
            $biomeId = Uuid::fromString($config['biome']);
        } else {
            $biomeId = Uuid::fromString(BiomeRepositoryConfig::OCEAN);
        }

        return new LocationTemplate(
            new Location(
                $locationId,
                $gameId,
                $biomeId,
                $coordinates,
                $this->getScavengingLevel($biomeId)
            ),
            $generatedEntities
        );
    }

    private function getScavengingLevel(UuidInterface $biomeId): int
    {
        switch ($biomeId->toString()) {
            case BiomeRepositoryConfig::OCEAN:
                return 0;
            case BiomeRepositoryConfig::ARABLE:
                return 5;
            case BiomeRepositoryConfig::URBAN:
                return 25;
        }
    }
}
